---
title: "halfproj_loading_books"
author: "Preet Patel"
date: "2025-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = "~/Downloads/STAT107 halfway project/books_1910s")
```

```{r}
install.packages(c("stringr", "tidyverse","magrittr"))
library(stringr)
library(tidyverse)
library(magrittr)
```


```{r}
files <- list.files(pattern = "\\.txt$")
files


books_1990s <- lapply(files, function(f) {
  readLines(f, encoding = "UTF-8") %>%
    str_trim() %>% #removes leading/trailing whitespace
    str_replace_all("\n", " ") %>%  # remove newline characters
    str_flatten(collapse = " ") %>%  # combine with spaces
    str_squish() %>%  # remove extra whitespace
    str_to_lower() #make lowercase
})
names(books_1990s) <- files

#str(books_1990s, max.level = 1)

# check first book
names(books_1990s)[1]
nchar(books_1990s[[1]])  # Character count
substr(books_1990s[[1]], 1, 200)  # First 200 characters

```


```{r}

```

